name: tests-payments

on:
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.STRIPE_KEY }} && cd payments && npm install && npm run test:ci
      - env: 
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}


      
